language: php

php:
  - 7.2

env:
  global:
    - REPO_NAME=cakephp-edexml
    - PLUGIN_NAME=Edexml
    - REQUIRE=""
    - DB=mysql CAKE_VERSION=2

    - secure: "kmIqmn7zQbmOuceFPERYUeGgL42iDeY61oHGFJIIbfGW9iZBTSO8FzZ0tYET2gdJU+8QOjImEaArddJRVclLPG/eSSlgxYx8jXGVMgoYctvqjOG8oNIfn/QtVSQuv6ZIre9tB/bY6zYYHlC+A6212BB5sIw6TnE7YyE0v0rjJrU="

  matrix:
    - CAKE_VERSION=2.9
    - CAKE_VERSION=2.10 PHPUNIT_VERSION=^5.7

matrix:
  include:
    - php: 7.2
      env:
        - CODECOVERAGE=1 PHPUNIT_VERSION=^5.7
    - php: 7.2
      env:
        - PHPCS=1
    - php: 7.2
      env:
        - FOC_VALIDATE=1
  exclude:
    - php: 7.2
      env: CAKE_VERSION=2.9

branches:
  only:
    - master

before_script:
  - git clone -b master https://github.com/Oefenweb/travis --depth 1 ../travis
  - travis_wait ../travis/before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
  hipchat:
    rooms:
      secure: TcF40BLcQ9tThuS/Le8NCGodmcfZ7dZLvil1gzjn8pvoQd13lEe8SYwBxEPjZK1xuJC9QBtkM5RNnT7DpiXpMDTGZvRGK/hSGdg/nHqqIqkAyyIMKt3xPQo/2eBmWXfsccb5axk6vvWM09Y53Csjiv19c/qQNcsGZG2mxdJh/sI=
